# CONFIG ENTRIES
CURRENT_DATA_DELTA_TABLE_NAME = "CURRENT_DATA_DELTA_TABLE_NAME"
DELTA_SRC_PATH = "DELTA_SRC"
POSTGRESQL_DB = "POSTGRESQL_DB"
POSTGRESQL_USER = "POSTGRESQL_USER"
POSTGRESQL_PASSWORD = "POSTGRESQL_PASSWORD"
POSTGRESQL_HOST = "POSTGRESQL_HOST"
KAFKA_SERVER = "KAFKA_SERVER"

# CONFIG VALUES - in separate source
CURRENT_DATA = "current_data"
DELTA_LOCATION = "delta/"
POSTGRESQL_DB_VALUE = "postgres"
POSTGRESQL_USER_VALUE = "kampus"
POSTGRESQL_PASSWORD_VALUE = "kampus"
POSTGRESQL_HOST_VALUE = "localhost"
KAFKA_SERVER_NAME = "localhost:9092"
